### ISSUE TITLE
get error after deploy to heroku dyno

### ISSUE THREAD

**Issue by m3u8ts** [sqeven/proxy#1]
hello seven ,
 
my heroku dyno build succeed log is :

-----> https://github.com/dockhero/heroku-buildpack-docker-compose.git app detected

-----> Using docker CLI 18.06.3

-----> Using docker-compose 1.25.2

-----> Installing binaries under /app/vendor

-----> Writing .profile.d script

-----> nginx-buildpack app detected

-----> nginx-buildpack: Installed nginx/1.18.0 to app/bin

-----> nginx-buildpack: Added start-nginx to app/bin

-----> nginx-buildpack: Added start-nginx-debug to app/bin

-----> nginx-buildpack: Added start-nginx-solo to app/bin

-----> nginx-buildpack: Default mime.types copied to app/config/

-----> nginx-buildpack: Default config copied to app/config.

-----> Discovering process types

       Procfile declares types -> (none)

-----> Compressing...

       Done: 15.8M

-----> Launching...

       Released v8

       https://mazetube.herokuapp.com/ deployed to Heroku

im using this two build pack to deploy :

https://github.com/dockhero/heroku-buildpack-docker-compose.git
https://github.com/heroku/heroku-buildpack-nginx.git

but after deployed complete get this error log :

https://gist.github.com/m3u8ts/df9370a72e46946d79c9cb0a7bceaa14

please help me to resolve it
waiting for your response
finest regards

**Comment by sqeven** [comment]
heroku to https://github.com/sqeven/siteproxy
you can use https://all.mk-proxy.tk/ OR https://google.fuckcloudnative.io/
